###############################################################
# Testbed Compute Containers
# 
# These are the compute containers needed for basic unit testing.
###############################################################

ssh:
  image: agaveapi/centos-base:latest
  hostname: docker.example.com
  ports:
    - '10111:22'
   
gsissh:
  image: agaveapi/gridftp:5
  hostname: docker.example.com
  ports:
    - '2222:2222'
    - '2022:22'

slurm:
  image: agaveapi/slurm:latest
  hostname: docker.example.com
  ports:
    - '10133:22'

torque:
  image: agaveapi/torque:latest
  hostname: docker.example.com
  privileged: true
  ports:
    - '10144:22'

htcondor:
  image: agaveapi/htcondor:latest
  hostname: docker.example.com
  ports:
    - '10155:22'

gridengine:
  image: agaveapi/gridengine:latest
  hostname: docker.example.com
  environment:
    - "HOSTNAME=docker.example.com"
  privileged: true
  ports:
    - '10166:22'
    - '6444:6444'
    - '6445:6445'
    
openlava:
  image: agaveapi/openlava:3.3
  hostname: docker.example.com
  ports:
    - '10177:22' 
    - '6879:6879'
    - '6878:6878'
    - '6882:6882'
    - '6881:6881'

