/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table Usage
# ------------------------------------------------------------

DROP TABLE IF EXISTS `Usage`;

CREATE TABLE `Usage` (
  `UID` int(11) NOT NULL AUTO_INCREMENT,
  `Username` varchar(64) NOT NULL,
  `ServiceKey` varchar(30) NOT NULL DEFAULT '',
  `ActivityKey` varchar(32) NOT NULL DEFAULT '',
  `ActivityContext` varchar(64) DEFAULT NULL,
  `CreatedAt` datetime NOT NULL,
  `CallingIP` varchar(15) DEFAULT NULL,
  `UserIP` varchar(15) DEFAULT NULL,
  `ClientApplication` varchar(64) NOT NULL DEFAULT '',
  `TenantId` varchar(64) NOT NULL DEFAULT '',
  `UserAgent` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`UID`),
  KEY `ServiceKey` (`ServiceKey`),
  KEY `ActivityKey` (`ActivityKey`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table UsageActivities
# ------------------------------------------------------------

DROP TABLE IF EXISTS `UsageActivities`;

CREATE TABLE `UsageActivities` (
  `id` int(200) NOT NULL AUTO_INCREMENT,
  `ActivityKey` varchar(32) NOT NULL DEFAULT '',
  `Description` text,
  `ServiceKey` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ServiceKey` (`ServiceKey`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `UsageActivities` WRITE;
/*!40000 ALTER TABLE `UsageActivities` DISABLE KEYS */;

INSERT INTO `UsageActivities` (`id`, `ActivityKey`, `Description`, `ServiceKey`)
VALUES
	(1,'AppsAdd','Publish application to apps service','Apps01'),
	(2,'AppsDelete','Delete application from apps service','Apps01'),
	(3,'AppsForm','Generate html form for a published app','Apps01'),
	(4,'AppsGetByID','Get application by specific id','Apps01'),
	(5,'AppsListPublic','List public apps','Apps01'),
	(6,'AppsListShared','List private apps','Apps01'),
	(7,'AppsSeachPublicByName','Find public app by name','Apps01'),
	(8,'AppsSeachPublicByTag','Find public app by tag','Apps01'),
	(9,'AppsSeachPublicByTerm','Find public app by term','Apps01'),
	(10,'AppsSeachSharedByName','Find shared app by name','Apps01'),
	(11,'AppsSeachSharedByTag','Find shared app by tag','Apps01'),
	(12,'AppsSeachSharedByTerm','Find shared app by term','Apps01'),
	(13,'AppsUsage','View apps service usage page','Apps01'),
	(14,'AtmoLaunch','Launch an Instance','Atm02'),
	(15,'AuthCreate','Create an auth token','Auth01'),
	(16,'AuthList','List all valid auth tokens','Auth01'),
	(17,'AuthRenew','Renew an auth token','Auth01'),
	(18,'AuthRevoke','Revoke an auth token','Auth01'),
	(19,'AuthVerify','Verify an auth token','Auth01'),
	(20,'claimit','redeem a postit','Postit01'),
	(21,'DataImpliedExport','Transform from native format to specified format and export','Data01'),
	(22,'DataImpliedTransform','Transform from native format to specified format','Data01'),
	(23,'DataList','List all available transforms','Data01'),
	(24,'DataSearchByFile','Search for transforms available for a file','Data01'),
	(25,'DataSearchByName','Search for transform by name','Data01'),
	(26,'DataSearchByTag','Search for transform by tag','Data01'),
	(27,'DataSpecifiedExport','Transform from specified format to specified format and export','Data01'),
	(28,'DataSpecifiedTransform','Transform from specified format to specified format','Data01'),
	(29,'DataViewCloud','View word cloud of data transform usage','Data01'),
	(30,'de-analysis-close','The Analysis window is closed','de-prod'),
	(31,'de-analysis-delete','','de-prod'),
	(32,'de-analysis-open','The Analysis window is opened','de-prod'),
	(33,'de-analysis-view-output','','de-prod'),
	(34,'de-apps-close','','de-prod'),
	(35,'de-apps-copy','','de-prod'),
	(36,'de-apps-delete','','de-prod'),
	(37,'de-apps-edit','','de-prod'),
	(38,'de-apps-fail','An app ran unsuccessfully','de-prod'),
	(39,'de-apps-fav','User rates or rerates an app','de-prod'),
	(40,'de-apps-launch-app','User launches an app','de-prod'),
	(41,'de-apps-make-public','','de-prod'),
	(42,'de-apps-new-app','','de-prod'),
	(43,'de-apps-new-workflow','','de-prod'),
	(44,'de-apps-open','','de-prod'),
	(45,'de-apps-open-app','User brings up the launch dialog for an app','de-prod'),
	(46,'de-apps-success','An app ran successfully','de-prod'),
	(47,'de-apps-unfav','User removes an app rating','de-prod'),
	(48,'de-data-close','The Data window is closed','de-prod'),
	(49,'de-data-file-delete','','de-prod'),
	(50,'de-data-file-download','','de-prod'),
	(51,'de-data-file-rename','','de-prod'),
	(52,'de-data-file-view','','de-prod'),
	(53,'de-data-folder-delete ','A folder is deleted','de-prod'),
	(54,'de-data-folder-new','A new folder is created','de-prod'),
	(55,'de-data-folder-rename','A folder is renamed','de-prod'),
	(56,'de-data-import-desktop','','de-prod'),
	(57,'de-data-import-url','','de-prod'),
	(58,'de-data-open','The Data window is opened','de-prod'),
	(59,'de-error','An error window appears','de-prod'),
	(60,'de-help-doc','User clicks the Documentation link','de-prod'),
	(61,'de-help-forums','User clicks the Forums link','de-prod'),
	(62,'de-help-support','User clicks the Support link','de-prod'),
	(63,'de-login','User logs into the DE','de-prod'),
	(64,'de-logout','User logs out of the DE','de-prod'),
	(65,'de-notif-close','','de-prod'),
	(66,'de-notif-new','User receives a new notification','de-prod'),
	(67,'de-notif-open','','de-prod'),
	(68,'de-notif-view','','de-prod'),
	(69,'IOCopy','Copy a file or folder','IO01'),
	(70,'IODelete','Delete a file or folder','IO01'),
	(71,'IODownload','Download a file','IO01'),
	(72,'IOExport','Async export a file','IO01'),
	(73,'IOImport','Async import a file','IO01'),
	(74,'IOList','List file or folder','IO01'),
	(75,'IOMakeDir','Create a new folder','IO01'),
	(76,'IOMove','Move file or folder','IO01'),
	(77,'IOPublicDownload','Download a public file','IO01'),
	(78,'IORename','Rename a file or folder','IO01'),
	(79,'IOShare','Manage share permissions on a file or folder','IO01'),
	(80,'IOUpload','Upload a file','IO01'),
	(81,'IOUsage','View io service usage page','IO01'),
	(82,'JobsDelete','Delete a job','Jobs01'),
	(83,'JobsGetByID','Get job by specific id','Jobs01'),
	(84,'JobsGetInput','Download input file from a job','Jobs01'),
	(85,'JobsGetOutput','Download output file from a job','Jobs01'),
	(86,'JobsKill','Kill a job','Jobs01'),
	(87,'JobsList','List a user\'s jobs','Jobs01'),
	(88,'JobsListInputs','List inputs for a job','Jobs01'),
	(89,'JobsListOutputs','List output path for a job','Jobs01'),
	(90,'JobsResubmit','Download output file from a job','Jobs01'),
	(91,'JobsShare','Manage share permissions on a job','Jobs01'),
	(92,'JobsSubmit','Submit a job','Jobs01'),
	(93,'JobsUsage','View jobs service usage page','Jobs01'),
	(94,'postit','create a new postit','Postit01'),
	(95,'ProfileSearchEmail','Search profile service with email address','Profile01'),
	(96,'ProfileSearchName','Search profile service with name','Profile01'),
	(97,'ProfileSearchUsername','Search profile service with username','Profile01'),
	(98,'ProfileUsage','View profile service usage page','Profile01'),
	(99,'ProfileUsername','Query profile service with username','Profile01'),
	(100,'revokeit','revoke a postit','Postit01'),
	(101,'tito-main-window','User clicks \"back\" for the landing screen','tito-prod'),
	(102,'de-login','User logs into the DE','de-qa'),
	(103,'de-logout','User logs out of the DE','de-qa'),
	(104,'de-data-open','The Data window is opened','de-qa'),
	(105,'de-data-close','The Data window is closed','de-qa'),
	(106,'de-data-folder-new','A new folder is created','de-qa'),
	(107,'de-data-folder-delete ','A folder is deleted','de-qa'),
	(108,'de-data-folder-rename','A folder is renamed','de-qa'),
	(109,'de-data-file-view','','de-qa'),
	(110,'de-data-file-rename','','de-qa'),
	(111,'de-data-file-delete','','de-qa'),
	(112,'de-data-file-download','','de-qa'),
	(113,'de-data-import-desktop','','de-qa'),
	(114,'de-data-import-url','','de-qa'),
	(115,'de-analysis-open','The Analysis window is opened','de-qa'),
	(116,'de-analysis-close','The Analysis window is closed','de-qa'),
	(117,'de-analysis-delete','','de-qa'),
	(118,'de-analysis-view-output','','de-qa'),
	(119,'de-apps-open','','de-qa'),
	(120,'de-apps-close','','de-qa'),
	(121,'de-apps-open-app','User brings up the launch dialog for an app','de-qa'),
	(122,'de-apps-launch-app','User launches an app','de-qa'),
	(123,'de-apps-success','An app ran successfully','de-qa'),
	(124,'de-apps-fail','An app ran unsuccessfully','de-qa'),
	(125,'de-apps-new-app','','de-qa'),
	(126,'de-apps-new-workflow','','de-qa'),
	(127,'de-apps-copy','','de-qa'),
	(128,'de-apps-edit','','de-qa'),
	(129,'de-apps-delete','','de-qa'),
	(130,'de-apps-make-public','','de-qa'),
	(131,'de-apps-fav','User rates or rerates an app','de-qa'),
	(132,'de-apps-unfav','User removes an app rating','de-qa'),
	(133,'de-notif-new','User receives a new notification','de-qa'),
	(134,'de-notif-open','','de-qa'),
	(135,'de-notif-close','','de-qa'),
	(136,'de-notif-view','','de-qa'),
	(137,'de-help-doc','User clicks the Documentation link','de-qa'),
	(138,'de-help-forums','User clicks the Forums link','de-qa'),
	(139,'de-help-support','User clicks the Support link','de-qa'),
	(140,'de-error','An error window appears','de-qa'),
	(141,'de-login','User logs into the DE','de-dev'),
	(142,'de-logout','User logs out of the DE','de-dev'),
	(143,'de-data-open','The Data window is opened','de-dev'),
	(144,'de-data-close','The Data window is closed','de-dev'),
	(145,'de-data-folder-new','A new folder is created','de-dev'),
	(146,'de-data-folder-delete ','A folder is deleted','de-dev'),
	(147,'de-data-folder-rename','A folder is renamed','de-dev'),
	(148,'de-data-file-view','','de-dev'),
	(149,'de-data-file-rename','','de-dev'),
	(150,'de-data-file-delete','','de-dev'),
	(151,'de-data-file-download','','de-dev'),
	(152,'de-data-import-desktop','','de-dev'),
	(153,'de-data-import-url','','de-dev'),
	(154,'de-analysis-open','The Analysis window is opened','de-dev'),
	(155,'de-analysis-close','The Analysis window is closed','de-dev'),
	(156,'de-analysis-delete','','de-dev'),
	(157,'de-analysis-view-output','','de-dev'),
	(158,'de-apps-open','','de-dev'),
	(159,'de-apps-close','','de-dev'),
	(160,'de-apps-open-app','User brings up the launch dialog for an app','de-dev'),
	(161,'de-apps-launch-app','User launches an app','de-dev'),
	(162,'de-apps-success','An app ran successfully','de-dev'),
	(163,'de-apps-fail','An app ran unsuccessfully','de-dev'),
	(164,'de-apps-new-app','','de-dev'),
	(165,'de-apps-new-workflow','','de-dev'),
	(166,'de-apps-copy','','de-dev'),
	(167,'de-apps-edit','','de-dev'),
	(168,'de-apps-delete','','de-dev'),
	(169,'de-apps-make-public','','de-dev'),
	(170,'de-apps-fav','User rates or rerates an app','de-dev'),
	(171,'de-apps-unfav','User removes an app rating','de-dev'),
	(172,'de-notif-new','User receives a new notification','de-dev'),
	(173,'de-notif-open','','de-dev'),
	(174,'de-notif-close','','de-dev'),
	(175,'de-notif-view','','de-dev'),
	(176,'de-help-doc','User clicks the Documentation link','de-dev'),
	(177,'de-help-forums','User clicks the Forums link','de-dev'),
	(178,'de-help-support','User clicks the Support link','de-dev'),
	(179,'de-error','An error window appears','de-dev'),
	(180,'de-login','User logs into the DE','de-staging'),
	(181,'de-logout','User logs out of the DE','de-staging'),
	(182,'de-data-open','The Data window is opened','de-staging'),
	(183,'de-data-close','The Data window is closed','de-staging'),
	(184,'de-data-folder-new','A new folder is created','de-staging'),
	(185,'de-data-folder-delete ','A folder is deleted','de-staging'),
	(186,'de-data-folder-rename','A folder is renamed','de-staging'),
	(187,'de-data-file-view','','de-staging'),
	(188,'de-data-file-rename','','de-staging'),
	(189,'de-data-file-delete','','de-staging'),
	(190,'de-data-file-download','','de-staging'),
	(191,'de-data-import-desktop','','de-staging'),
	(192,'de-data-import-url','','de-staging'),
	(193,'de-analysis-open','The Analysis window is opened','de-staging'),
	(194,'de-analysis-close','The Analysis window is closed','de-staging'),
	(195,'de-analysis-delete','','de-staging'),
	(196,'de-analysis-view-output','','de-staging'),
	(197,'de-apps-open','','de-staging'),
	(198,'de-apps-close','','de-staging'),
	(199,'de-apps-open-app','User brings up the launch dialog for an app','de-staging'),
	(200,'de-apps-launch-app','User launches an app','de-staging'),
	(201,'de-apps-success','An app ran successfully','de-staging'),
	(202,'de-apps-fail','An app ran unsuccessfully','de-staging'),
	(203,'de-apps-new-app','','de-staging'),
	(204,'de-apps-new-workflow','','de-staging'),
	(205,'de-apps-copy','','de-staging'),
	(206,'de-apps-edit','','de-staging'),
	(207,'de-apps-delete','','de-staging'),
	(208,'de-apps-make-public','','de-staging'),
	(209,'de-apps-fav','User rates or rerates an app','de-staging'),
	(210,'de-apps-unfav','User removes an app rating','de-staging'),
	(211,'de-notif-new','User receives a new notification','de-staging'),
	(212,'de-notif-open','','de-staging'),
	(213,'de-notif-close','','de-staging'),
	(214,'de-notif-view','','de-staging'),
	(215,'de-help-doc','User clicks the Documentation link','de-staging'),
	(216,'de-help-forums','User clicks the Forums link','de-staging'),
	(217,'de-help-support','User clicks the Support link','de-staging'),
	(218,'de-error','An error window appears','de-staging'),
	(219,'tito-login','','tito-prod'),
	(220,'tito-logout','','tito-prod'),
	(221,'tito-create-new','','tito-prod'),
	(222,'tito-edit','','tito-prod'),
	(223,'tito-copy','','tito-prod'),
	(224,'tito-publish','','tito-prod'),
	(225,'tito-request-install','','tito-prod'),
	(226,'tito-delete','','tito-prod'),
	(227,'tito-save','','tito-prod'),
	(228,'tito-preview-ui','','tito-prod'),
	(229,'tito-preview-json','','tito-prod'),
	(230,'tito-help-doc','User clicks the Documentation link','tito-prod'),
	(231,'tito-help-forums','User clicks the Forums link','tito-prod'),
	(232,'tito-help-support','User clicks the Support link','tito-prod'),
	(233,'tito-error','An error window appears','tito-prod'),
	(234,'tito-login','','tito-de'),
	(235,'tito-logout','','tito-de'),
	(236,'tito-create-new','','tito-de'),
	(237,'tito-edit','','tito-de'),
	(238,'tito-copy','','tito-de'),
	(239,'tito-publish','','tito-de'),
	(240,'tito-request-install','','tito-de'),
	(241,'tito-delete','','tito-de'),
	(242,'tito-save','','tito-de'),
	(243,'tito-preview-ui','','tito-de'),
	(244,'tito-preview-json','','tito-de'),
	(245,'tito-main-window','User clicks \"back\" for the landing screen','tito-de'),
	(246,'tito-help-doc','User clicks the Documentation link','tito-de'),
	(247,'tito-help-forums','User clicks the Forums link','tito-de'),
	(248,'tito-help-support','User clicks the Support link','tito-de'),
	(249,'tito-error','An error window appears','tito-de'),
	(250,'tito-login','','tito-qa'),
	(251,'tito-logout','','tito-qa'),
	(252,'tito-create-new','','tito-qa'),
	(253,'tito-edit','','tito-qa'),
	(254,'tito-copy','','tito-qa'),
	(255,'tito-publish','','tito-qa'),
	(256,'tito-request-install','','tito-qa'),
	(257,'tito-delete','','tito-qa'),
	(258,'tito-save','','tito-qa'),
	(259,'tito-preview-ui','','tito-qa'),
	(260,'tito-preview-json','','tito-qa'),
	(261,'tito-main-window','User clicks \"back\" for the landing screen','tito-qa'),
	(262,'tito-help-doc','User clicks the Documentation link','tito-qa'),
	(263,'tito-help-forums','User clicks the Forums link','tito-qa'),
	(264,'tito-help-support','User clicks the Support link','tito-qa'),
	(265,'tito-error','An error window appears','tito-qa'),
	(266,'tito-login','','tito-staging'),
	(267,'tito-logout','','tito-staging'),
	(268,'tito-create-new','','tito-staging'),
	(269,'tito-edit','','tito-staging'),
	(270,'tito-copy','','tito-staging'),
	(271,'tito-publish','','tito-staging'),
	(272,'tito-request-install','','tito-staging'),
	(273,'tito-delete','','tito-staging'),
	(274,'tito-save','','tito-staging'),
	(275,'tito-preview-ui','','tito-staging'),
	(276,'tito-preview-json','','tito-staging'),
	(277,'tito-main-window','User clicks \"back\" for the landing screen','tito-staging'),
	(278,'tito-help-doc','User clicks the Documentation link','tito-staging'),
	(279,'tito-help-forums','User clicks the Forums link','tito-staging'),
	(280,'tito-help-support','User clicks the Support link','tito-staging'),
	(281,'tito-error','An error window appears','tito-staging'),
	(282,'belph-categ-add','','belphegor-prod'),
	(283,'belph-categ-delete','','belphegor-prod'),
	(284,'belph-categ-rename','','belphegor-prod'),
	(285,'belph-categ-move','User moves a subcategory to a different parent','belphegor-prod'),
	(286,'belph-categ-expand','User expands the categories panel','belphegor-prod'),
	(287,'belph-categ-collapse','User collapses the categories panel','belphegor-prod'),
	(288,'belph-app-delete','','belphegor-prod'),
	(289,'belph-app-edit','User opens the edit dialog','belphegor-prod'),
	(290,'belph-app-recateg','User moves an app to a different category','belphegor-prod'),
	(291,'belph-app-expand','User expands an app','belphegor-prod'),
	(292,'belph-app-save','User clicks \"save\" in the edit dialog','belphegor-prod'),
	(293,'belph-app-doc','User clicks the Documentation link for an app','belphegor-prod'),
	(294,'belph-app-forum','User clicks the Forum link for an app','belphegor-prod'),
	(295,'belph-categ-add','','belphegor-qa'),
	(296,'belph-categ-delete','','belphegor-qa'),
	(297,'belph-categ-rename','','belphegor-qa'),
	(298,'belph-categ-move','User moves a subcategory to a different parent','belphegor-qa'),
	(299,'belph-categ-expand','User expands the categories panel','belphegor-qa'),
	(300,'belph-categ-collapse','User collapses the categories panel','belphegor-qa'),
	(301,'belph-app-delete','','belphegor-qa'),
	(302,'belph-app-edit','User opens the edit dialog','belphegor-qa'),
	(303,'belph-app-recateg','User moves an app to a different category','belphegor-qa'),
	(304,'belph-app-expand','User expands an app','belphegor-qa'),
	(305,'belph-app-save','User clicks \"save\" in the edit dialog','belphegor-qa'),
	(306,'belph-app-doc','User clicks the Documentation link for an app','belphegor-qa'),
	(307,'belph-app-forum','User clicks the Forum link for an app','belphegor-qa'),
	(308,'belph-error','An error window appears','belphegor-qa'),
	(309,'belph-categ-add','','belphegor-dev'),
	(310,'belph-categ-delete','','belphegor-dev'),
	(311,'belph-categ-rename','','belphegor-dev'),
	(312,'belph-categ-move','User moves a subcategory to a different parent','belphegor-dev'),
	(313,'belph-categ-expand','User expands the categories panel','belphegor-dev'),
	(314,'belph-categ-collapse','User collapses the categories panel','belphegor-dev'),
	(315,'belph-app-delete','','belphegor-dev'),
	(316,'belph-app-edit','User opens the edit dialog','belphegor-dev'),
	(317,'belph-app-recateg','User moves an app to a different category','belphegor-dev'),
	(318,'belph-app-expand','User expands an app','belphegor-dev'),
	(319,'belph-app-save','User clicks \"save\" in the edit dialog','belphegor-dev'),
	(320,'belph-app-doc','User clicks the Documentation link for an app','belphegor-dev'),
	(321,'belph-app-forum','User clicks the Forum link for an app','belphegor-dev'),
	(322,'belph-error','An error window appears','belphegor-dev'),
	(323,'belph-categ-add','','belphegor-staging'),
	(324,'belph-categ-delete','','belphegor-staging'),
	(325,'belph-categ-rename','','belphegor-staging'),
	(326,'belph-categ-move','User moves a subcategory to a different parent','belphegor-staging'),
	(327,'belph-categ-expand','User expands the categories panel','belphegor-staging'),
	(328,'belph-categ-collapse','User collapses the categories panel','belphegor-staging'),
	(329,'belph-app-delete','','belphegor-staging'),
	(330,'belph-app-edit','User opens the edit dialog','belphegor-staging'),
	(331,'belph-app-recateg','User moves an app to a different category','belphegor-staging'),
	(332,'belph-app-expand','User expands an app','belphegor-staging'),
	(333,'belph-app-save','User clicks \"save\" in the edit dialog','belphegor-staging'),
	(334,'belph-app-doc','User clicks the Documentation link for an app','belphegor-staging'),
	(335,'belph-app-forum','User clicks the Forum link for an app','belphegor-staging'),
	(336,'belph-error','An error window appears','belphegor-staging'),
	(337,'JobSearch','Search for foundation jobs','Jobs01'),
	(338,'JobsListAttribute','List specific attribute of foundation jobs','Jobs01'),
	(339,'SystemsList','List iPlant HPC systems','Systems01'),
	(340,'MonitorDaily','Show daily test results','Monitor01'),
	(341,'MonitorTest','Show individual test results','Monitor01'),
	(342,'MonitorSummary','Show summary results','Monitor01'),
	(343,'MonitorSuite','Show results from a test suite','Monitor01'),
	(344,'MonitorService','Show results from an test group','Monitor01'),
	(345,'PostItCreate','Create a new PostIt link','PostIt01'),
	(346,'PostItClaim','Claim a PostIt link','PostIt01'),
	(347,'PostItRevoke','Revoke a PostIt link','PostIt01'),
	(348,'AppsPublish','Publish an app to the public space','Apps01'),
	(349,'AppsListPermissions','List app permissions','Apps01'),
	(350,'AppsEditPermissions','Edit app permissions','Apps01'),
	(351,'SystemsUsage','Systems service usage info','Systems01'),
	(352,'AppsDelete','','APPS02'),
	(353,'AppsForm','','APPS02'),
	(354,'AppsGetByID','','APPS02'),
	(355,'AppsList','','APPS02'),
	(356,'AppsListPublic','','APPS02'),
	(357,'AppsListShared','','APPS02'),
	(358,'AppsAdd','','APPS02'),
	(359,'AppsSearchPublicByName','','APPS02'),
	(360,'AppsSearchPublicByTag','','APPS02'),
	(361,'AppsSearchPublicByTerm','','APPS02'),
	(362,'AppsSearchSharedByName','','APPS02'),
	(363,'AppsSearchSharedByTag','','APPS02'),
	(364,'AppsSearchSharedByTerm','','APPS02'),
	(365,'AppsUsage','','APPS02'),
	(366,'AppsListPermissions','','APPS02'),
	(367,'AppsPublish','','APPS02'),
	(368,'AppsSearchPublicBySystem','','APPS02'),
	(369,'AppsUpdatePermissions','','APPS02'),
	(370,'AppsRemovePermissions','','APPS02'),
	(371,'AuthCreate','','AUTH02'),
	(372,'AuthList','','AUTH02'),
	(373,'AuthRenew','','AUTH02'),
	(374,'AuthRevoke','','AUTH02'),
	(375,'DataImpliedExport','','TRANSFORMS02'),
	(376,'DataImpliedTransform','','TRANSFORMS02'),
	(377,'DataList','','TRANSFORMS02'),
	(378,'DataSearchByFile','','TRANSFORMS02'),
	(379,'DataSearchByName','','TRANSFORMS02'),
	(380,'DataSearchByTag','','TRANSFORMS02'),
	(381,'DataSpecifiedExport','','TRANSFORMS02'),
	(382,'DataSpecifiedTransform','','TRANSFORMS02'),
	(383,'DataViewCloud','','TRANSFORMS02'),
	(384,'IOPublicDownload','','FILES02'),
	(385,'IOMove','','FILES02'),
	(386,'IOMakeDir','','FILES02'),
	(387,'IOCopy','','FILES02'),
	(388,'IODelete','','FILES02'),
	(389,'IODownload','','FILES02'),
	(390,'IOExport','','FILES02'),
	(391,'IOImport','','FILES02'),
	(392,'IOList','','FILES02'),
	(393,'IORename','','FILES02'),
	(394,'IOShare','','FILES02'),
	(395,'IOUpload','','FILES02'),
	(396,'IOUsage','','FILES02'),
	(397,'FilesGetHistory','','FILES02'),
	(398,'JobsDelete','','JOBS02'),
	(399,'JobsGetByID','','JOBS02'),
	(400,'JobsGetOutput','','JOBS02'),
	(401,'JobsKill','','JOBS02'),
	(402,'JobsList','','JOBS02'),
	(403,'JobsListInputs','','JOBS02'),
	(404,'JobsResubmit','','JOBS02'),
	(405,'JobsListOutputs','','JOBS02'),
	(406,'JobsShare','','JOBS02'),
	(407,'JobsSubmit','','JOBS02'),
	(408,'JobsGetInput','','JOBS02'),
	(409,'JobsUsage','','JOBS02'),
	(410,'JobStatus','','JOBS02'),
	(411,'JobSearch','','JOBS02'),
	(412,'JobAttributeList','','JOBS02'),
	(413,'JobsGetHistory','','JOBS02'),
	(414,'JobSubmissionForm','','JOBS02'),
	(415,'InternalUsersList','','PROFILES02'),
	(416,'InternalUsersRegistration','','PROFILES02'),
	(417,'InternalUserDelete','','PROFILES02'),
	(418,'InternalUserUpdate','','PROFILES02'),
	(419,'InternalUserGet','','PROFILES02'),
	(420,'InternalUserSearchName','','PROFILES02'),
	(421,'InternalUserSearchEmail','','PROFILES02'),
	(422,'InternalUserSearchUsername','','PROFILES02'),
	(423,'InternalUserSearchStatus','','PROFILES02'),
	(424,'SystemGetCredentials','','SYSTEMS02'),
	(425,'SystemAddCredential','','SYSTEMS02'),
	(426,'SystemRemoveCredential','','SYSTEMS02'),
	(427,'SystemsListPublic','','SYSTEMS02'),
	(428,'SystemsGetByID','','SYSTEMS02'),
	(429,'SystemsAdd','','SYSTEMS02'),
	(430,'SystemsDelete','','SYSTEMS02'),
	(431,'SystemsPublish','','SYSTEMS02'),
	(432,'SystemsUnpublish','','SYSTEMS02'),
	(433,'SystemsClone','','SYSTEMS02'),
	(434,'SystemsSetDefault','','SYSTEMS02'),
	(435,'SystemsUnsetDefault','','SYSTEMS02'),
	(436,'SystemsSetGlobalDefault','','SYSTEMS02'),
	(437,'SystemsUnsetGlobalDefault','','SYSTEMS02'),
	(438,'SystemListRoles','','SYSTEMS02'),
	(439,'SystemEditRoles','','SYSTEMS02'),
	(440,'SystemRemoveRoles','','SYSTEMS02'),
	(441,'SystemsDefaultListPublic','','SYSTEMS02'),
	(442,'SystemsErase','','SYSTEMS02'),
	(443,'UsageList','','USAGE02'),
	(444,'UsageSearch','','USAGE02'),
	(445,'UsageAddTrigger','','USAGE02'),
	(446,'UsageDeleteTrigger','','USAGE02'),
	(447,'UsageUpdateTrigger','','USAGE02'),
	(448,'SchemaList','','METADATA02'),
	(449,'SchemaListRelated','','METADATA02'),
	(450,'SchemaGetById','','METADATA02'),
	(451,'SchemaSearch','','METADATA02'),
	(452,'SchemaCreate','','METADATA02'),
	(453,'SchemaDelete','','METADATA02'),
	(454,'SchemaEdit','','METADATA02'),
	(455,'SchemaPemsCreate','','METADATA02'),
	(456,'SchemaPemsAdd','','METADATA02'),
	(457,'SchemaPemsUpdate','','METADATA02'),
	(458,'SchemaPemsDelete','','METADATA02'),
	(459,'SchemaPemsList','','METADATA02'),
	(460,'NotifList','','NOTIFICATIONS02'),
	(461,'NotifAdd','','NOTIFICATIONS02'),
	(462,'NotifUpdate','','NOTIFICATIONS02'),
	(463,'NotifDelete','','NOTIFICATIONS02'),
	(464,'NotifTrigger','','NOTIFICATIONS02'),
	(465,'NotifListRelated','','NOTIFICATIONS02'),
	(466,'NotifGetById','','NOTIFICATIONS02'),
	(467,'PostItList','','POSTITS02'),
	(468,'PostItsDelete','','POSTITS02'),
	(469,'PostItRedeem','','POSTITS02'),
	(470,'PostItsAdd','','POSTITS02'),
	(471,'TransfersList','','TRANSFERS02'),
	(472,'TransfersAdd','','TRANSFERS02'),
	(473,'TransfersUpdate','','TRANSFERS02'),
	(474,'TransfersDelete','','TRANSFERS02'),
	(475,'TransfersStop','','TRANSFERS02'),
	(476,'TransfersSearch','','TRANSFERS02'),
	(477,'TransfersGetById','','TRANSFERS02'),
	(478,'TriggerListAll','','TRIGGERS02'),
	(479,'TriggerCreate','','TRIGGERS02'),
	(480,'TriggerList','','TRIGGERS02'),
	(481,'TriggerDelete','','TRIGGERS02'),
	(482,'MyProxyList','','MYPROXY02'),
	(483,'MyProxyStore','','MYPROXY02'),
	(484,'MyProxyGetByName','','MYPROXY02'),
	(485,'MyProxyDelete','','MYPROXY02'),
	(486,'InternalUserClear','','PROFILES02'),
	(487,'AuthVerify','','AUTH02'),
	(488,'SystemsListAll','','SYSTEMS02'),
	(489,'SystemsListType','','SYSTEMS02'),
	(490,'SystemsSearch','','SYSTEMS02'),
	(491,'SystemsUpdate','','SYSTEMS02'),
	(492,'MetaCreate','','METADATA02'),
	(493,'MetaList','','METADATA02'),
	(494,'MetaListRelated','','METADATA02'),
	(495,'MetaGetById','','METADATA02'),
	(496,'MetaSearch','','METADATA02'),
	(497,'MetaDelete','','METADATA02'),
	(498,'MetaEdit','','METADATA02'),
	(499,'MetaPemsCreate','','METADATA02'),
	(500,'MetaPemsAdd','','METADATA02'),
	(501,'MetaPemsUpdate','','METADATA02'),
	(502,'MetaPemsDelete','','METADATA02'),
	(503,'MetaPemsList','','METADATA02');

/*!40000 ALTER TABLE `UsageActivities` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table UsageDeveloper
# ------------------------------------------------------------

DROP TABLE IF EXISTS `UsageDeveloper`;

CREATE TABLE `UsageDeveloper` (
  `Username` varchar(64) NOT NULL DEFAULT '',
  `ServiceKey` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`Username`,`ServiceKey`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `UsageDeveloper` WRITE;
/*!40000 ALTER TABLE `UsageDeveloper` DISABLE KEYS */;

INSERT INTO `UsageDeveloper` (`Username`, `ServiceKey`)
VALUES
	('dennis','belphegor-dev'),
	('dennis','belphegor-prod'),
	('dennis','belphegor-qa'),
	('dennis','belphegor-staging'),
	('dennis','de-dev'),
	('dennis','de-prod'),
	('dennis','de-qa'),
	('dennis','de-staging'),
	('dennis','tito-de'),
	('dennis','tito-prod'),
	('dennis','tito-qa'),
	('dennis','tito-staging'),
	('hariolf','belphegor-dev'),
	('hariolf','belphegor-prod'),
	('hariolf','belphegor-qa'),
	('hariolf','belphegor-staging'),
	('hariolf','de-dev'),
	('hariolf','de-prod'),
	('hariolf','de-qa'),
	('hariolf','de-staging'),
	('hariolf','tito-de'),
	('hariolf','tito-prod'),
	('hariolf','tito-qa'),
	('hariolf','tito-staging'),
	('ipctest','Atm02'),
	('jerry','belphegor-dev'),
	('jerry','belphegor-prod'),
	('jerry','belphegor-qa'),
	('jerry','belphegor-staging'),
	('jerry','de-dev'),
	('jerry','de-prod'),
	('jerry','de-qa'),
	('jerry','de-staging'),
	('jerry','tito-de'),
	('jerry','tito-prod'),
	('jerry','tito-qa'),
	('jerry','tito-staging'),
	('lenards','belphegor-dev'),
	('lenards','belphegor-prod'),
	('lenards','belphegor-qa'),
	('lenards','belphegor-staging'),
	('lenards','de-dev'),
	('lenards','de-prod'),
	('lenards','de-qa'),
	('lenards','de-staging'),
	('lenards','tito-de'),
	('lenards','tito-prod'),
	('lenards','tito-qa'),
	('lenards','tito-staging'),
	('psarando','belphegor-dev'),
	('psarando','belphegor-prod'),
	('psarando','belphegor-qa'),
	('psarando','belphegor-staging'),
	('psarando','de-dev'),
	('psarando','de-prod'),
	('psarando','de-qa'),
	('psarando','de-staging'),
	('psarando','tito-de'),
	('psarando','tito-prod'),
	('psarando','tito-qa'),
	('psarando','tito-staging'),
	('sriram','belphegor-dev'),
	('sriram','belphegor-prod'),
	('sriram','belphegor-qa'),
	('sriram','belphegor-staging'),
	('sriram','de-dev'),
	('sriram','de-prod'),
	('sriram','de-qa'),
	('sriram','de-staging'),
	('sriram','tito-de'),
	('sriram','tito-prod'),
	('sriram','tito-qa'),
	('sriram','tito-staging');

/*!40000 ALTER TABLE `UsageDeveloper` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table UsageServices
# ------------------------------------------------------------

DROP TABLE IF EXISTS `UsageServices`;

CREATE TABLE `UsageServices` (
  `ID` int(200) NOT NULL AUTO_INCREMENT,
  `ServiceKey` varchar(30) NOT NULL DEFAULT '',
  `Description` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `UsageServices` WRITE;
/*!40000 ALTER TABLE `UsageServices` DISABLE KEYS */;

INSERT INTO `UsageServices` (`ID`, `ServiceKey`, `Description`)
VALUES
	(1,'Apps01','Foundation Apps Service v1'),
	(2,'Atm01','iPlant Cloud Environment'),
	(3,'Atm02','atmosphere'),
	(4,'Auth01','Foundation Auth Service v1'),
	(5,'belphegor','DE Admin GUI  - Production'),
	(6,'belphegor-dev','DE Admin GUI  - Dev'),
	(7,'belphegor-qa','DE Admin GUI  - QA'),
	(8,'belphegor-staging','DE Admin GUI - Staging'),
	(9,'Data01','Foundation Data Service v1'),
	(10,'de-dev','Discovery Environment - Dev'),
	(11,'de-prod','Discovery Environment Production'),
	(12,'de-qa','Discovery Environment - QA'),
	(13,'de-staging','Discovery Environment Production'),
	(14,'DE002','Bioinformatic Workflows'),
	(15,'IO01','Foundation IO Service v1'),
	(16,'Jobs01','Foundation Job service v1'),
	(17,'Postit01','foundation api postit service'),
	(18,'Profile01','Foundation Profile Service v1'),
	(19,'tito-de','Tools Integration - Discovery Environment'),
	(20,'tito-prod','Tools Integration - Production'),
	(21,'tito-qa','Tools Integration - QA'),
	(22,'tito-staging','Tools Integration - Staging'),
	(23,'Systems01','Foundation Systems Service v1'),
	(24,'Monitor01','Foundation monitoring service v1'),
	(25,'PostIt01','Foundation PostIt service v1'),
	(26,'APPS02','Apps Service V2'),
	(27,'AUTH02','Auth Service V2'),
	(28,'TRANSFORMS02','Transforms Service V2'),
	(29,'FILES02','Files Service V2'),
	(30,'JOBS02','Jobs Service V2'),
	(31,'PROFILES02','Profiles Service V2'),
	(32,'SYSTEMS02','Systems Service V2'),
	(33,'USAGE02','Usage Service V2'),
	(34,'METADATA02','Metadata Service V2'),
	(35,'NOTIFICATIONS02','Notifications Service V2'),
	(36,'POSTITS02','Postits Service V2'),
	(37,'TRANSFERS02','Transfers Service V2'),
	(38,'TRIGGERS02','Triggers Service V2'),
	(39,'MYPROXY02','Myproxy Service V2');

/*!40000 ALTER TABLE `UsageServices` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
